#!/bin/bash
# Bash script to run all unit tests before every commit
# Saved in .git/hooks

echo "You are about to commit. Running test files to check for errors."


#Run Unit Tests
###############
VENV="venv_mac/bin/python3.9"

${VENV} -m unittest discover -v tests/scripts/

if [ $? -eq 0 ]; then
   echo "Tests passed. Continue with commit."
   exit 0

else
   echo "Some tests failed. Aborting the commit."
   exit 1
fi

