#!/bin/bash
# Bash script to run all unit tests before every commit
# Saved in .git/hooks

echo "You are about to commit. Running test files to check for errors."


#Run Unit Tests
###############
source venv_mac/bin/activate

python3.9 -m unittest discover -v tests/scripts/

if [ $? -eq 0 ]; then
   echo "Tests passed. Continue with commit."
   exit 0

else
   echo "Some tests failed. Aborting the commit."
   exit 1
fi


# End of script
# Path: pre-commit
# You must make the script executable by running chmod +x pre-commit
# You must also make commits from the terminal for it to work.